#!/bin/bash

# 現在のディレクトリを表示
echo "Current directory: $(pwd)"

# ステージングを解除する関数
unstage_changes() {
	echo "UnStaging changes..."
	git restore --staged .
}

# チェックを実行する関数
run_check() {
	local check_name=$1
	local make_target=$2

	echo ""
	echo "_____________________________________"
	echo "Running $check_name..."
	make $make_target
	if [ $? -ne 0 ]; then
		echo "$check_name failed. Commit aborted."
		unstage_changes
		exit 1
	fi
}

# 各種チェックの実行
run_check "golangci-lint" "golint"
run_check "staticcheck" "staticcheck"
# run_check "deadcode" "deadcode"
run_check "gosec" "gosec"

# すべてのチェックに合格
echo ""
echo "_____________________________________"
echo "All checks passed. Proceeding with commit."
exit 0
