#!/bin/bash

# 現在のディレクトリを表示
echo "Current directory: $(pwd)"

# ステージングを解除する関数
unstage_changes() {
	echo "UnStaging changes..."
	git restore --staged .
}

# golangci-lint の実行
echo ""
echo "_____________________________________"
echo "Running golangci-lint..."
make golint
if [ $? -ne 0 ]; then
	echo "golangci-lint failed. Commit aborted."
	unstage_changes
	exit 1
fi

# staticcheck の実行
echo ""
echo "_____________________________________"
echo "Running staticcheck..."
make staticcheck
if [ $? -ne 0 ]; then
	echo "staticcheck failed. Commit aborted."
	unstage_changes
	exit 1
fi

# # deadcode の実行
# echo ""
# echo "_____________________________________"
# echo "Running deadcode..."
# make deadcode
# if [ $? -ne 0 ]; then
# 	echo "deadcode failed. Commit aborted."
# 	unstage_changes
# 	exit 1
# fi

# gosec の実行
echo ""
echo "_____________________________________"
echo "Running gosec..."
make gosec
if [ $? -ne 0 ]; then
	echo "gosec detected issues. Commit aborted."
	unstage_changes
	exit 1
fi

# すべてのチェックに合格
echo ""
echo "_____________________________________"
echo "All checks passed. Proceeding with commit."
exit 0
