###  ==============================
GET http://localhost:1234/v1/person?name=a
Content-Type: application/json


###  ==============================
GET http://localhost:1234/v1/person?mailAddress=bbbb@gmail.com
Content-Type: application/json


###  ==============================
GET http://localhost:1234/v1/person/viaGRPC?name=a
Content-Type: application/json


###  ==============================
GET http://localhost:1234/v1/person/viaGRPC?mailAddress=bb@gmail.com
Content-Type: application/json

