@YOUR_JWT_TOKEN=
# 保護されたエンドポイント (JWTトークンが必要)
GET http://localhost:8080/protected HTTP/1.1
Authorization: Bearer {{YOUR_JWT_TOKEN}}
Content-Type: application/json


###
# get access token
POST https://dev-fe00zeb23uke8zls.us.auth0.com/oauth/token
Content-Type: application/json

{
  "client_id": "jVHOlYQKt6Tgkrf670NpRdEaSmm8ZCdX",
  "client_secret": "ZbT0VUI6Txyxj2oyxoOhO2fYSFe6U4eIbhdquIyoQX6kqr-J3iFN7fSyfy8CHWYq",
  "audience": "https://auth0my-yayuji.com",
  "grant_type": "client_credentials"
}


###
# get access token
POST http://localhost:1234/v1/auth/withmiddleware/fetchAccessToken
Content-Type: application/json

{
  "client_id": "jVHOlYQKt6Tgkrf670NpRdEaSmm8ZCdX",
  "client_secret": "ZbT0VUI6Txyxj2oyxoOhO2fYSFe6U4eIbhdquIyoQX6kqr-J3iFN7fSyfy8CHWYq"
}
