
### --------------------------------
proto < ../../parameter/grpc/person.proto
GRPC localhost:3456/grpc_parameter.Person/GetPersonByCondition
{
	"v1PersonParameter": {
		"mailAddress": "aaaa@gmail.com"
	}
}

### --------------------------------
proto < ../../parameter/grpc/person.proto
GRPC localhost:3456/grpc_parameter.Person/GetPersonByCondition
{
	"v1PersonParameter": {
		"name": "b"
	}
}

### --------------------------------
proto < ../../parameter/grpc/person.proto
GRPC localhost:3456/grpc_parameter.Person/GetPersonByCondition
{
	"common": {
		"traceID": "test-trace-id",
		"timestamp": "2024-01-01T00:00:00Z"
	},
	"parameter": {
		"id": 1,
		"name": "test user",
		"mail_address": "test@example.com"
	}
}
