@hostname=localhost
# @hostname=192.168.10.8
@port=5678

@yakisoba=4548779706595
@yakionig=4902150657300
@pastaika=4548779734116
@pastakan=4548779734192
@dummy___=1111111111111

@languageCodeJa=1041
@languageCodeEn=1033
@languageCodeEs=1034
@languageCodeZh=2052
@languageCodeAr=14337

@queryParam=?debug=true
# @queryParam=?debug=false


### / ===============================================
GET https://{{hostname}}:{{port}}

### admin_product ==============================
PATCH https://{{hostname}}:{{port}}/v1/admin/product/{{pastaika}}{{queryParam}}
Content-Type: application/json

{
	"is_valid": true,
	"place": "aaaa"
}

### casher ===============================================
### --------------------------------------------
DELETE https://{{hostname}}:{{port}}/v1/casher{{queryParam}}
Content-Type: application/json

{
	"sold_no" : 7,
	"status" : 1,
	"language_code" : {{languageCodeJa}} ,
	"jan_code_list" : [
	]
}

### --------------------------------------------
POST https://{{hostname}}:{{port}}/v1/casher{{queryParam}}
Content-Type: application/json
 
{
	"sold_no" : 4,
	"status" : 1,
	"jan_code_list" : [
		{{languageCodeAr}},
		{{pastakan}},
		{{yakionig}},
		{{dummy___}}
	]
}



### delivery_queue ===============================================
### --------------------------------------------
PATCH https://{{hostname}}:{{port}}/v1/delivery{{queryParam}}
Content-Type: application/json

{
	"sold_no" : 4,
	"status" : 2
}


# languageCodeJa
# languageCodeEn
# languageCodeEs
# languageCodeZh
# languageCodeAr

### client/queue ===============================================
POST https://{{hostname}}:{{port}}/v1/client/queue/1{{queryParam}}
Content-Type: application/json

{
	"jan_code_list" : [
		{{languageCodeJa}},
		{{pastakan}},
		{{pastakan}},
		{{pastakan}},
		{{yakionig}},
		{{dummy___}}
	]
}


### --------------------------------------------
DELETE https://{{hostname}}:{{port}}/v1/client/queue/0{{queryParam}}
Content-Type: application/json

{
}


### --------------------------------------------
GET https://{{hostname}}:{{port}}/v1/client/queue/0{{queryParam}}

### --------------------------------------------
GET https://{{hostname}}:{{port}}/v1/client/queue/1{{queryParam}}

### --------------------------------------------
GET https://{{hostname}}:{{port}}/v1/client/queue/2{{queryParam}}

### --------------------------------------------
GET https://{{hostname}}:{{port}}/v1/client/queue/3{{queryParam}}

### --------------------------------------------
GET https://{{hostname}}:{{port}}/v1/client/queue/4{{queryParam}}



