// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: backend/internal/1_framework/input/grpc/person/person.proto

package person

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type V1PersonParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                     // ID
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`                                  // Name
	MailAddress   *string                `protobuf:"bytes,3,opt,name=mail_address,json=mailAddress,proto3,oneof" json:"mail_address,omitempty"` // Mail Address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PersonParameter) Reset() {
	*x = V1PersonParameter{}
	mi := &file_backend_internal_1_framework_input_grpc_person_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PersonParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PersonParameter) ProtoMessage() {}

func (x *V1PersonParameter) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_1_framework_input_grpc_person_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PersonParameter.ProtoReflect.Descriptor instead.
func (*V1PersonParameter) Descriptor() ([]byte, []int) {
	return file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescGZIP(), []int{0}
}

func (x *V1PersonParameter) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *V1PersonParameter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *V1PersonParameter) GetMailAddress() string {
	if x != nil && x.MailAddress != nil {
		return *x.MailAddress
	}
	return ""
}

type V1PersonParameterArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       []*V1PersonParameter   `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"` // Array of V1PersonParameter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1PersonParameterArray) Reset() {
	*x = V1PersonParameterArray{}
	mi := &file_backend_internal_1_framework_input_grpc_person_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1PersonParameterArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1PersonParameterArray) ProtoMessage() {}

func (x *V1PersonParameterArray) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_1_framework_input_grpc_person_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1PersonParameterArray.ProtoReflect.Descriptor instead.
func (*V1PersonParameterArray) Descriptor() ([]byte, []int) {
	return file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescGZIP(), []int{1}
}

func (x *V1PersonParameterArray) GetPersons() []*V1PersonParameter {
	if x != nil {
		return x.Persons
	}
	return nil
}

var File_backend_internal_1_framework_input_grpc_person_person_proto protoreflect.FileDescriptor

var file_backend_internal_1_framework_input_grpc_person_person_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x31, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x11, 0x56, 0x31, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x13, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x6d, 0x61, 0x69,
	0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x0b, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x4d, 0x0a, 0x16, 0x56, 0x31, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x33, 0x0a, 0x07,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x73, 0x32, 0x5b, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x1e,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x41, 0x72, 0x72, 0x61, 0x79, 0x42, 0x57,
	0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x75, 0x6a,
	0x69, 0x59, 0x61, 0x62, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x31, 0x5f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescOnce sync.Once
	file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescData = file_backend_internal_1_framework_input_grpc_person_person_proto_rawDesc
)

func file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescGZIP() []byte {
	file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescOnce.Do(func() {
		file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescData)
	})
	return file_backend_internal_1_framework_input_grpc_person_person_proto_rawDescData
}

var file_backend_internal_1_framework_input_grpc_person_person_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backend_internal_1_framework_input_grpc_person_person_proto_goTypes = []any{
	(*V1PersonParameter)(nil),      // 0: person.V1PersonParameter
	(*V1PersonParameterArray)(nil), // 1: person.V1PersonParameterArray
}
var file_backend_internal_1_framework_input_grpc_person_person_proto_depIdxs = []int32{
	0, // 0: person.V1PersonParameterArray.persons:type_name -> person.V1PersonParameter
	0, // 1: person.Person.GetPersonByCondition:input_type -> person.V1PersonParameter
	1, // 2: person.Person.GetPersonByCondition:output_type -> person.V1PersonParameterArray
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_backend_internal_1_framework_input_grpc_person_person_proto_init() }
func file_backend_internal_1_framework_input_grpc_person_person_proto_init() {
	if File_backend_internal_1_framework_input_grpc_person_person_proto != nil {
		return
	}
	file_backend_internal_1_framework_input_grpc_person_person_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_internal_1_framework_input_grpc_person_person_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_internal_1_framework_input_grpc_person_person_proto_goTypes,
		DependencyIndexes: file_backend_internal_1_framework_input_grpc_person_person_proto_depIdxs,
		MessageInfos:      file_backend_internal_1_framework_input_grpc_person_person_proto_msgTypes,
	}.Build()
	File_backend_internal_1_framework_input_grpc_person_person_proto = out.File
	file_backend_internal_1_framework_input_grpc_person_person_proto_rawDesc = nil
	file_backend_internal_1_framework_input_grpc_person_person_proto_goTypes = nil
	file_backend_internal_1_framework_input_grpc_person_person_proto_depIdxs = nil
}
