
### --------------------------------
proto < ./person.proto
GRPC localhost:3456/person.Person/GetPersonByCondition
{
	"mailAddress": "bbbb@gmail.com"
}

### --------------------------------
proto < ./person.proto
GRPC localhost:3456/person.Person/GetPersonByCondition
{
	"name": "a"
}

### --------------------------------
