

### --------------------------------
proto < ../../../grpc_parameter/person.proto
GRPC localhost:3456/grpc_parameter.Person/GetPersonByCondition
{
	"mailAddress": "bbbb@gmail.com"
}

### --------------------------------
proto < ../../../grpc_parameter/person.proto
GRPC localhost:3456/grpc_parameter.Person/GetPersonByCondition
{
	"name": "a"
}

### --------------------------------
