@baseUrl = http://localhost:{{goEchoPort}}

### --------------------------------
GET {{baseUrl}}/v1/health
Accept: text/plain

### --------------------------------
GET {{baseUrl}}/v1/nonexistent
Accept: application/json
