GET http://localhost:1234/users?name=a
Accept: application/json

##--------------------------------
GET http://localhost:53234/users?mailAddress=bbbb@gmail.com
Accept: application/json

##--------------------------------
POST http://localhost:53234/users
Content-Type: application/json

{
	"name": "New User",
	"email": "new.user@example.com"
}

##--------------------------------
GET http://localhost:53234/health
Accept: text/plain


##--------------------------------
GET http://localhost:53234/nonexistent
Accept: application/json


##--------------------------------

