GET http://localhost:53234/v1/users?name=a
Accept: application/json

### --------------------------------
GET http://localhost:53234/v1/users?email=bbbb@gmail.com
Accept: application/json

### --------------------------------
POST http://localhost:53234/v1/users
Content-Type: application/json

{
	"name": "New User",
	"email": "new.user@example.com"
}

### --------------------------------
GET http://localhost:53234/v1/health
Accept: text/plain


### --------------------------------
GET http://localhost:53234/v1/nonexistent
Accept: application/json


### --------------------------------
GET http://localhost:53234/v1/to-pubsub
Accept: application/json

### --------------------------------
GET http://localhost:53234/v1/validation-word-rules?targetType=name&isBlacklist=true
Accept: application/json

### --------------------------------
POST http://localhost:53234/v1/validation-word-rules
Content-Type: application/json

{
	"targetType": "name",
	"isBlacklist": true,
	"word": "root"
}

### --------------------------------
PUT http://localhost:53234/v1/validation-word-rules
Content-Type: application/json

{
	"targetType": "name",
	"isBlacklist": true,
	"oldWord": "root",
	"newWord": "admin"
}

### --------------------------------
DELETE http://localhost:53234/v1/validation-word-rules
Content-Type: application/json

{
	"targetType": "name",
	"isBlacklist": true,
	"word": "admin"
}
